<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <AssemblyName>UncomplicatedCustomEscapeZones</AssemblyName>
        <RootNamespace>UncomplicatedEscapeZones</RootNamespace>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PlatformTarget>x64</PlatformTarget>
        <Platforms>x64</Platforms>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <Nullable>disable</Nullable>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>embedded</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <OutputPath>bin\x64\Debug\</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
        <DebugType>embedded</DebugType>
        <Optimize>true</Optimize>
        <DefineConstants>TRACE</DefineConstants>
        <OutputPath>bin\x64\Release\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" PrivateAssets="all"/>
        <PackageReference Include="Northwood.LabAPI" Version="1.1.6.1"/>
        <PackageReference Include="System.Net.Http" Version="4.3.4"/>
        <PackageReference Include="System.Text.Json" Version="10.0.1"/>
        <PackageReference Include="YamlDotNet" Version="11.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="CommandSystem.Core" HintPath="$(sl_references)\CommandSystem.Core.dll"/>
        <Reference Include="NorthwoodLib" HintPath="$(sl_references)\NorthwoodLib.dll"/>
        <Reference Include="Assembly-CSharp" HintPath="$(sl_references)\Assembly-CSharp.dll" Publicize="true"/>
        <Reference Include="Assembly-CSharp-firstpass" HintPath="$(sl_references)\Assembly-CSharp-firstpass.dll"/>
        <Reference Include="Mirror" HintPath="$(sl_references)\Mirror.dll"/>
        <Reference Include="UnityEngine.CoreModule" HintPath="$(sl_references)\UnityEngine.CoreModule.dll"/>
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <Exec Command="xcopy &quot;$(TargetPath)&quot; &quot;$(labapi_plugins)\&quot; /y"/>
    </Target>

</Project>
